# Learning about toml and experimenting with it
# toml might not be the best tool for this particular config file
[category-names]
chemistry = "Chemistry"
markets = "Markets"
health = "Health"
energy = "Energy"
contextual-study = "Words Used In Several Context"
favorites = "Favorites"
marine = "Marine Life"
food-drinks = "Food And Drinks"
places = "Places and Regions"
computing = "Computing/Digital"
entertainment = "Entertainment"
natural-disaster = "Natural Disasters"

[[markets]]
hz = "央行"
en = "central bank"

[[markets]]
hz = "货币政策"
en = "monetary policy"

[[markets]]
hz = "通胀"
en = "inflation"

[[markets]]
hz = "通货膨胀"
en = "inflation"

[[markets]]
hz = "滞胀"
en = "stagflation"

[[markets]]
hz = "量化宽松"
en = "quantitative easing"

[[markets]]
hz = "缩减购债"
en = "taper; tapering"

[[markets]]
hz = "消费者"
en = "consumer"

[[markets]]
hz = "零售商"
en = "retailer"

[[markets]]
hz = "散户"
en =  "retail investors"

[[markets]]
hz = "投资者"
en = "investor"

[[markets]]
hz = "投资"
en = "invest"

[[markets]]
hz = "金融"
en = "finance"

[[markets]]
hz = "期货"
en = "futures"

[[markets]]
hz = "期权"
en = "option"

[[markets]]
hz = "模因股"
en = "meme stock"

[[markets]]
hz = "价格"
en = "price"

[[markets]]
hz = "利润"
en = "profit"

[[markets]]
hz = "盈利"
en = "profit"

[[markets]]
hz = "成本"
en = "costs (production, manufacturing)"

[[markets]]
hz = "收入"
en = "income; revenue; receipts; earnings; proceeds"

[[markets]]
hz = "订单"
en = "order for goods; order form"

[[markets]]
hz = "税"
en = "tax; duty"

[[markets]]
hz = "税收"
en = "tax revenue"

[[markets]]
hz = "关税"
en = "tariff; customs duty"

[[markets]]
hz = "放缓"
en = "to slow down; decelerate"

[[markets]]
hz = "区块链"
en = "blockchain"

[[markets]]
hz = "加密货币"
en = "cryptocurrency"

[[markets]]
hz = "比特币"
en = "bitcoin"

[[markets]]
hz = "数字货币"
en = "digital currency"

[[markets]]
hz = "预测"
en = "forecast"

[[markets]]
hz = "需求"
en = "demand"

[[markets]]
hz = "短缺"
en = "shortage"

[[markets]]
hz = "反垄断"
en = "antitrust"

[[markets]]
hz = "劳动"
en = "labor"

[[markets]]
hz = "贸易"
en = "trade"

[[markets]]
hz = "净进口国"
en = "net importer"

[[markets]]
hz = "退市"
en = "delist"

[[markets]]
hz = "开盘"
en = "opening quotation"

[[markets]]
hz = "收盘价"
en = "closing price"

[[markets]]
hz = "市值"
en = "market value; market cap"

[[markets]]
hz = "超额配"
en = "oversubscribed"


[[contextual-study]]
hz = "盐"
en = "salt"

[[contextual-study]]
hz = "获得"
en = "gain; obtain; acquire; win; achieve"

[[contextual-study]]
hz = "趋势"
en = "trend"

[[contextual-study]]
hz = "冲击"
en = "impact; shock; to attack"

[[contextual-study]]
hz = "爆发"
en = "erupt; burst out; break out"

[[contextual-study]]
hz = "瓶颈"
en = "bottleneck"

[[contextual-study]]
hz = "效率"
en = "efficiency"

[[contextual-study]]
hz = "超过"
en = "exceed"

[[contextual-study]]
hz = "情况"
en = "circumstances; situation"

[[contextual-study]]
hz = "严重"
en = "serious; grave; severe; critical"

[[contextual-study]]
hz = "取消"
en = "cancel"

[[contextual-study]]
hz = "影响"
en = "to have an effect on; to influence; to affect; to have an impact on; to disturb"

[[contextual-study]]
hz = "紧急"
en = "urgent; emergency; pressing"

[[contextual-study]]
hz = "政策"
en = "policy"

[[contextual-study]]
hz = "刺激"
en = "stimulus; stimulation; incentive; stimulate;uree on ; encourage"

[[contextual-study]]
hz = "暂停"
en = "suspend"

[[contextual-study]]
hz = "核心"
en = "core; center; most important part"

[[contextual-study]]
hz = "崛起"
en = "to rise abruptly; to emerge suddenly; the emergence (e.g. of  a power)"

[[contextual-study]]
hz = "平衡"
en = "balance; equilibrium"

[[contextual-study]]
hz = "发布"
en = "issue; release"

[[contextual-study]]
hz = "推出"
en = "launch; release; publish; introduce; put out"

[[contextual-study]]
hz = "威胁"
en = "threaten; menace; imperil"

[[contextual-study]]
hz = "放射线"
en = "radiation"

[[contextual-study]]
hz = "担忧"
en = "to worry; to be concerned; be anxious"

[[contextual-study]]
hz = "担心"
en = "worry; feel anxious"

[[contextual-study]]
hz = "批准"
en = "ratify; approve; sanction"

[[contextual-study]]
hz = "不确定性"
en = "uncertainty"


[[favorites]]
hz = "供应链"
en = "supply chain"

[[favorites]]
hz = "港口"
en = "port"

[[favorites]]
hz = "物流"
en = "logistics"

[[favorites]]
hz = "箱船"
en = "container ship"

[[favorites]]
hz = "散货船"
en = "bulk freighter"

[[favorites]]
hz = "航线"
en = "air or shipping line; route; course"

[[favorites]]
hz = "半导体"
en = "semiconductor"

[[favorites]]
hz = "芯片"
en = "chip"

[[favorites]]
hz = "纳米"
en = "nanometer"

[[favorites]]
hz = "摩尔定律"
en = "Moore’s Law"

[[favorites]]
hz = "堆叠"
en = "stack (as in 3D stacking)"

[[favorites]]
hz = "后工序"
en = "post-process"

[[favorites]]
hz = "陶瓷"
en = "ceramics; porcelein"

[[favorites]]
hz = "晶体管"
en = "transistor"

[[favorites]]
hz = "晶圆"
en = "wafer"

[[favorites]]
hz = "液晶"
en = "liquid crystal"

[[favorites]]
hz = "多晶硅"
en = "polycrystalline silicon"

[[favorites]]
hz = "模拟"
en = "analog; simulation; to simulate"

[[favorites]]
hz = "量子"
en = "quantum"

[[favorites]]
hz = "波长"
en = "wavelength"

[[favorites]]
hz = "微波"
en = "microwave"

[[favorites]]
hz = "滤波器"
en = "wave filter"

[[favorites]]
hz = "光合作用"
en = "photosynthesis"

[[favorites]]
hz = "光子"
en = "photon"

[[favorites]]
hz = "光伏"
en = "photovoltaic"

[[favorites]]
hz = "光刻"
en = "lithography"

[[favorites]]
hz = "光纤"
en = "optical fiber"

[[favorites]]
hz = "发光二极管"
en = "LED"

[[favorites]]
hz = "电磁"
en = "electromagnetic; electromagnetism"

[[favorites]]
hz = "电池"
en = "battery"

[[favorites]]
hz = "稀土"
en = "rare earth"

[[favorites]]
hz = "微细化"
en = "miniaturization"

[[favorites]]
hz = "小型化"
en = "miniaturization"

[[favorites]]
hz = "传感器"
en = "sensor"

[[favorites]]
hz = "激光雷达"
en = "lidar"

[[favorites]]
hz = "红外"
en = "infrared"

[[favorites]]
hz = "二维码"
en = "QR code"

[[favorites]]
hz = "零部件"
en = "parts and components"

[[favorites]]
hz = "机床"
en = "machine tools"

[[favorites]]
hz = "螺丝"
en = "screws"

[[favorites]]
hz = "基础设施"
en = "infrastructure"

[[favorites]]
hz = "塑料"
en = "plastic"

[[favorites]]
hz = "氨基酸"
en = "amino acids"

[[favorites]]
hz = "蛋白质"
en = "protein"

[[favorites]]
hz = "信使核糖核酸"
en = "mRNA"

[[favorites]]
hz = "尼安德特人"
en = "neanderthal"

[[favorites]]
hz = "恐龙"
en = "dinosaur "

[[favorites]]
hz = "千足虫"
en = "millipede"

[[favorites]]
hz = "液压挖掘机"
en = "hydraulic excavator"

[[favorites]]
hz = "叉车"
en = "forklift"

[[favorites]]
hz = "拖拉机"
en = "tractor"

[[favorites]]
hz = "铁臂阿童木"
en = "Astro Boy"

[[favorites]]
hz = "小行星"
en = "asteroid"

[[favorites]]
hz = "宇宙"
en = "universe; cosmos; space; void"

[[favorites]]
hz = "望远镜"
en = "telescope"

[[favorites]]
hz = "闭路"
en = "closed-circuit"

[[favorites]]
hz = "熔岩"
en = "lava"

[[favorites]]
hz = "海水淡化"
en = "seawater desalination"

[[favorites]]
hz = "圣诞"
en = "Christmas"

[[favorites]]
hz = "曙光"
en = "first light of morning; dawn"

[[favorites]]
hz = "尾部风险"
en = "tail risk"


[[health]]
hz = "新型冠状病毒"
en = "novel coronavirus"

[[health]]
hz = "冠病病毒"
en = "coronavirus"

[[health]]
hz = "冠病疫苗"
en = "coronavirus vaccine"

[[health]]
hz = "德尔塔变异毒株"
en = "delta mutant strain"

[[health]]
hz = "奥密克戎变种"
en = "omicron variant"

[[health]]
hz = "出现症状前"
en = "presymptomatic"

[[health]]
hz = "无症状"
en = "asymptomatic"

[[health]]
hz = "大流行"
en = "pandemic"

[[health]]
hz = "疫情"
en = "epidemic"

[[health]]
hz = "流行病学"
en = "epidemiology"

[[health]]
hz = "病毒学家"
en = "virologist"

[[health]]
hz = "暴發"
en = "outbreak"

[[health]]
hz = "住院"
en = "hospitalization"

[[health]]
hz = "氧气"
en = "oxygen (gas)"

[[health]]
hz = "飞沫"
en = "droplet"

[[health]]
hz = "气溶胶"
en = "aerosol"

[[health]]
hz = "感冒"
en = "cold"

[[health]]
hz = "流感"
en = "flu"

[[health]]
hz = "感染"
en = "infection"

[[health]]
hz = "传染性"
en = "infectiousness; contagiousness; contagion"

[[health]]
hz = "病例"
en = "case (medical)"

[[health]]
hz = "检疫隔离"
en = "quarantine"

[[health]]
hz = "口罩"
en = "surgical mask"

[[health]]
hz = "核酸检测"
en = "nucleic acid test"

[[health]]
hz = "聚合酶链式反应"
en = "polymerase chain reaction"

[[health]]
hz = "心肌炎"
en = "myocarditis"

[[health]]
hz = "心包炎"
en = "pericarditis"

[[health]]
hz = "腺病毒"
en = "adenovirus"

[[health]]
hz = "免疫缺陷"
en = "immunodeficiency"

[[health]]
hz = "脑雾"
en = "brain fog"

[[health]]
hz = "脑血栓"
en = "cerebral thrombus"

[[health]]
hz = "血清"
en = "(blood) serum"

[[health]]
hz = "血压"
en = "blood pressure"

[[health]]
hz = "血栓"
en = "blood clot; thrombus"

[[health]]
hz = "血糖"
en = "blood sugar"

[[health]]
hz = "血癌"
en = "leukemia"

[[health]]
hz = "白血球"
en = "white blood cell"

[[health]]
hz = "糖尿病"
en = "diabetes"

[[health]]
hz = "癌症"
en = "cancer"

[[health]]
hz = "瘤"
en = "tumor"

[[health]]
hz = "放疗"
en = "radiotherapy"

[[health]]
hz = "抗体"
en = "antibodies"

[[health]]
hz = "重症"
en = "acute; grave"

[[health]]
hz = "疾病"
en = "disease; illness"

[[health]]
hz = "阿尔茨海默"
en = "Alzheimer"

[[health]]
hz = "肥胖症"
en = "obesity"

[[health]]
hz = "白内障"
en = "cataract"

[[health]]
hz = "医疗"
en = "medical or surgical treatment; therapy"

[[health]]
hz = "治疗"
en = "to treat(an illness); medical treatment; therapy"

[[health]]
hz = "痊愈"
en = "fully recover from an illness; completely cured/recovered"

[[health]]
hz = "护士"
en = "nurse"


[[energy]]
hz = "天然气"
en = "natural gas"

[[energy]]
hz = "液化天然气"
en = "LNG"

[[energy]]
hz = "燃料"
en = "fuel"

[[energy]]
hz = "化石"
en = "fossil"

[[energy]]
hz = "石油"
en = "oil/petroleum"

[[energy]]
hz = "原油"
en = "crude oil"

[[energy]]
hz = "柴油"
en = "diesel oil"

[[energy]]
hz = "油砂"
en = "oil sands"

[[energy]]
hz = "煤炭"
en = "coal"

[[energy]]
hz = "核能"
en = "nuclear energy"

[[energy]]
hz = "脱碳"
en = "decarbonization"

[[energy]]
hz = "温室气体"
en = "greenhouse gas"

[[energy]]
hz = "净零排放"
en = "net zero emissions"

[[energy]]
hz = "可再生能源"
en = "renewable energy"


[[chemistry]]
hz = "原子"
en = "atom"

[[chemistry]]
hz = "离子"
en = "ion"

[[chemistry]]
hz = "氢"
en = "hydrogen"

[[chemistry]]
hz = "氦"
en = "helium"

[[chemistry]]
hz = "锂"
en = "lithium"

[[chemistry]]
hz = "碳"
en = "carbon"

[[chemistry]]
hz = "氮"
en = "nitrogen"

[[chemistry]]
hz = "钠"
en = "sodium"

[[chemistry]]
hz = "镁"
en = "magnesium"

[[chemistry]]
hz = "铝"
en = "aluminum"

[[chemistry]]
hz = "硅"
en = "silicon"

[[chemistry]]
hz = "硫"
en = "sulfur"

[[chemistry]]
hz = "钴"
en = "cobalt"

[[chemistry]]
hz = "镍"
en = "nickel"

[[chemistry]]
hz = "铜"
en = "copper"

[[chemistry]]
hz = "锌"
en = "zinc"

[[chemistry]]
hz = "镓"
en = "gallium"

[[chemistry]]
hz = "锗"
en = "germanium"

[[chemistry]]
hz = "铟"
en = "indium"

[[chemistry]]
hz = "铑"
en = "rhodium"

[[chemistry]]
hz = "钯"
en = "palladium"

[[chemistry]]
hz = "钕"
en = "neodynium"

[[chemistry]]
hz = "镝"
en = "dysprosium"

[[chemistry]]
hz = "铅"
en = "lead"

[[chemistry]]
hz = "鐳"
en = "radium"

[[chemistry]]
hz = "锕"
en = "actinium"

[[chemistry]]
hz = "钍"
en = "thorium"

[[chemistry]]
hz = "铀"
en = "uranium"

[[chemistry]]
hz = "二氧化碳"
en = "carbon dioxide"

[[chemistry]]
hz = "一氧化二氮"
en = "nitrous oxide"

[[chemistry]]
hz = "氨"
en = "ammonia"

[[chemistry]]
hz = "甲烷"
en = "methane"

[[chemistry]]
hz = "石墨烯"
en = "graphene"

[[chemistry]]
hz = "铁矿石"
en = "iron ore"

[[chemistry]]
hz = "锂矿石"
en = "lithium ore"

[[chemistry]]
hz = "磷酸铁锂"
en = "lithium iron phosphate"

[[chemistry]]
hz = "钴酸锂"
en = "lithium cobalt oxide"

[[chemistry]]
hz = "钛酸锂"
en = "lithium titanate"

[[chemistry]]
hz = "碳化硅"
en = "silicon carbide"

[[chemistry]]
hz = "乳酸"
en = "lactic acid"

[[chemistry]]
hz = "葡萄糖"
en = "glucose"

[[chemistry]]
hz = "蒸馏"
en = "distil; distillation"


[[marine]]
hz = "海胆"
en = "sea urchin"

[[marine]]
hz = "海藻"
en = "seaweed"

[[marine]]
hz = "海豚"
en = "dolphin"

[[marine]]
hz = "鲨鱼"
en = "shark"

[[marine]]
hz = "鲸"
en = "whale"

[[marine]]
hz = "章鱼"
en = "octopus"

[[marine]]
hz = "堡礁"
en = "barrier reef"


[[food-drinks]]
hz = "肉骨茶"
en = "bak-kut-teh or pork ribs soup"

[[food-drinks]]
hz = "拉面"
en = "ramen"

[[food-drinks]]
hz = "金枪鱼"
en = "tuna"

[[food-drinks]]
hz = "石斑鱼"
en = "grouper"

[[food-drinks]]
hz = "罗汉果"
en = "mangosteen"

[[food-drinks]]
hz = "榴梿"
en = "durian"

[[food-drinks]]
hz = "凤梨"
en = "pineapple"

[[food-drinks]]
hz = "月饼"
en = "mooncake"

[[food-drinks]]
hz = "披萨"
en = "pizza"

[[food-drinks]]
hz = "咖啡"
en = "coffee"

[[food-drinks]]
hz = "奶茶"
en = "milk tea"

[[food-drinks]]
hz = "啤酒"
en = "beer"

[[food-drinks]]
hz = "葡萄酒"
en = "wine"

[[food-drinks]]
hz = "清酒"
en = "sake"

[[food-drinks]]
hz = "威士忌"
en = "whiskey"


[[places]]
hz = "菲律宾"
en = "Philippines"

[[places]]
hz = "槟城"
en = "Penang"

[[places]]
hz = "东南亚"
en = "Southeast Asia"

[[places]]
hz = "福建"
en = "Hokkien (Fujian in Mandarin)"

[[places]]
hz = "北海道"
en = "Hokkaido"

[[places]]
hz = "冰岛"
en = "Iceland"

[[places]]
hz = "黑山"
en = "Montenegro"

[[places]]
hz = "加拉帕戈斯群岛"
en = "Galapagos Islands"

[[places]]
hz = "加利福尼亚"
en = "California"

[[places]]
hz = "得克萨斯"
en = "Texas"

[[places]]
hz = "佛罗里达"
en = "Florida"


[[computing]]
hz = "互联网"
en = "Internet"

[[computing]]
hz = "线上"
en = "online"

[[computing]]
hz = "元宇宙"
en = "metaverse"

[[computing]]
hz = "数码化"
en = "digitize; digitalize"

[[computing]]
hz = "硬盘"
en = "hard disk"

[[computing]]
hz = "面部识别"
en = "facial recognition"


[[entertainment]]
hz = "动画"
en = "animation; cartoon"

[[entertainment]]
hz = "漫画"
en = "manga; cartoon"

[[entertainment]]
hz = "科幻"
en = "scifi"

[[entertainment]]
hz = "邓紫棋"
en = "G.E.M."

[[entertainment]]
hz = "泰勒丝"
en = "Taylor Swift"

[[entertainment]]
hz = "漫威"
en = "Marvel"

[[entertainment]]
hz = "蜘蛛侠"
en = "Spiderman"

[[entertainment]]
hz = "黑寡妇"
en = "Black Widow"

[[entertainment]]
hz = "罗纳尔多"
en = "Cristiano Ronaldo"

[[entertainment]]
hz = "曼联"
en = "Manchester United"


[[natural-disaster]]
hz = "台风"
en = "typhoon"

[[natural-disaster]]
hz = "龙卷风"
en = "tornado"

[[natural-disaster]]
hz = "海啸"
en = "tsunami"

[[natural-disaster]]
hz = "地震"
en = "earthquake"

[[natural-disaster]]
hz = "洪灾"
en = "flood"

[[natural-disaster]]
hz = "沙尘暴"
en = "sandstorm; dust storm"

[[natural-disaster]]
hz = "暴雨"
en = "torrential rain; rainstorm"

[[natural-disaster]]
hz = "喷发"
en = "eruption"
